### ISSUE TITLE
Не запускается

### ISSUE THREAD

**Issue by kmurachev** [alexbers/tgsocksproxy#3]
```
[root@tgsocksproxy]# python3 /opt/tgsocksproxy/tgsocksproxy.py
tg://socks?server=YOUR_IP&port=3255&user=tg&pass=pass
tg://socks?server=YOUR_IP&port=3255&user=tg2&pass=pass2
Traceback (most recent call last):
  File "/opt/tgsocksproxy/tgsocksproxy.py", line 314, in <module>
    main()
  File "/opt/tgsocksproxy/tgsocksproxy.py", line 297, in main
    server = loop.run_until_complete(task)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/asyncio/streams.py", line 85, in start_server
    return await loop.create_server(factory, host, port, **kwds)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: BaseEventLoop.create_server() got an unexpected keyword argument 'loop'
[root@tgsocksproxy]# python3 -V
Python 3.11.4
[root@tgsocksproxy]# python -V
Python 3.11.4
```

ОС CentOS 8

**Comment by alexbers** [comment]
эту бага должна быть уже исправлена в ветке master, попробуйте с ней

**Comment by kmurachev** [comment]
я c этой ветки и брал

**Comment by alexbers** [comment]
а, всё, понял, это я не в тот проект посмотрел, сейчас поправлю

**Comment by alexbers** [comment]
поправил: https://github.com/alexbers/tgsocksproxy/commit/508d51ede0cc96111606db058c47cedb642ab9bf. Проверьте, что всё ок, плз

**Comment by kmurachev** [comment]
сегодня вечером обязательно проверю,
отпишусь

**Comment by kmurachev** [comment]
теперь всё прекрасно работает

благодарю 🍺

**Comment by kmurachev** [comment]
сделал по аналогии с https://github.com/alexbers/mtprotoproxy/issues/293#issue-1805708574

```
cd /opt
```
```
git clone https://github.com/alexbers/tgsocksproxy.git; cd tgsocksproxy
```
```
nano ./config.py
```
```
PORT = 3255
USERS = {"tg": "pass", "tg2": "pass2"}
```
```
useradd --no-create-home -s /usr/sbin/nologin tgsproxy
```
```
nano /etc/systemd/system/tgsocksproxy.service
```
```
[Unit]
    Description=Async socks proxy for Telegram
    After=network-online.target
    Wants=network-online.target

[Service]
    ExecStart=/opt/tgsocksproxy/tgsocksproxy.py
    AmbientCapabilities=CAP_NET_BIND_SERVICE
    LimitNOFILE=infinity
    User=tgsproxy
    Group=tgsproxy
    Restart=on-failure

[Install]
    WantedBy=multi-user.target

```
```
firewall-cmd --permanent --add-port=3255/tcp
```
```
firewall-cmd --permanent --add-port=3255/udp
```
```
firewall-cmd --reload
```
```
firewall-cmd --list-all
```
```
systemctl daemon-reload
```
```
systemctl restart tgsocksproxy
```
```
systemctl status tgsocksproxy
```
```
systemctl enable tgsocksproxy
```

**Comment by kmurachev** [comment]
выше справедливо для CentOS 8, там всё чётко, без ошибок

проверил на Ubuntu 22.04 -- там вот такая бага вылазит:
```
# python3 /opt/tgsocksproxy/tgsocksproxy.py
tg://socks?server=YOUR_IP&port=3255&user=tg&pass=pass
tg://socks?server=YOUR_IP&port=3255&user=tg2&pass=pass2
/opt/tgsocksproxy/tgsocksproxy.py:292: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()
/opt/tgsocksproxy/tgsocksproxy.py:293: DeprecationWarning: There is no current event loop
  stats_printer_task = asyncio.Task(stats_printer())
^C
Task was destroyed but it is pending!
task: <Task pending name='Task-6' coro=<handle_client.<locals>.connect_reader_to_writer() done, defined at /opt/tgsocksproxy/tgsocksproxy.py:225> wait_for=<Future pending cb=[Task.task_wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-7' coro=<handle_client.<locals>.connect_reader_to_writer() done, defined at /opt/tgsocksproxy/tgsocksproxy.py:225> wait_for=<Future pending cb=[Task.task_wakeup()]>>
# python3 -V
Python 3.10.6
# python -V
Python 3.10.6

```

как я понимаю, нет даты и статистики по каждой связке логин/пароль,
а так прокси работает

**Comment by alexbers** [comment]
закомитил ещё одно изменение, которое может исправить ошибку: https://github.com/alexbers/tgsocksproxy/commit/125e65933c850ce2c976e7920178f119c24c22b5

Попробуйте с ним

**Comment by kmurachev** [comment]
CentOS 8

```
# python3 /opt/tgsocksproxy/tgsocksproxy.py
tg://socks?server=YOUR_IP&port=3255&user=tg&pass=pass
tg://socks?server=YOUR_IP&port=3255&user=tg2&pass=pass2
^C
# python3 -V
Python 3.11.4
# 
```


Ubuntu 22.02

```
# python3 /opt/tgsocksproxy/tgsocksproxy.py
tg://socks?server=YOUR_IP&port=3255&user=tg&pass=pass
tg://socks?server=YOUR_IP&port=3255&user=tg2&pass=pass2
/opt/tgsocksproxy/tgsocksproxy.py:294: DeprecationWarning: There is no current event loop
  stats_printer_task = asyncio.Task(stats_printer())
^C
# python3 -V
Python 3.10.6
# 

```

**Comment by alexbers** [comment]
обновил ещё раз, дропнул поддержку python 3.6

**Comment by kmurachev** [comment]
да, теперь на Ubuntu 22.02 ошибки ушли
